<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>log</string>
		<string>v8.log</string>
	</array>
	<key>name</key>
	<string>V8 tick processor log</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#firstline</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#regexp</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#path</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#support</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#section</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>constant</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?x)
  \b(
    ([0-9]+(\.[0-9]+))|
    ([0-9]+)
  )\b</string>
					<key>name</key>
					<string>constant.numeric.v8.log</string>
				</dict>
			</array>
		</dict>
		<key>firstline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^(Statistical).*$\n?</string>
					<key>name</key>
					<string>comment.line.firstline.v8.log</string>
				</dict>
			</array>
		</dict>
		<key>function</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?x)
  \b(
    fs\.(
      readFileSync
    )|
    Buffer\.(
      write|toString
    )|
    anonymous
  )\b</string>
					<key>name</key>
					<string>entity.name.function.v8.log</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.v8.log</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.type.v8.log</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)
  \b((
    DELETE|
    join|
    parseInt|match|filter|
    defineProperties|decodeURIComponent|
    split|
  )\s+(native))\b</string>
				</dict>
			</array>
		</dict>
		<key>keyword</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^\s*((ticks|total|nonlib|name|cpp|parent)\s*)+$</string>
					<key>name</key>
					<string>keyword.operator.v8.log</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?x)
  \b(
    native
  )\b</string>
					<key>name</key>
					<string>support.type.v8.log</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?x)
  \s(
    ~|\*
  )</string>
					<key>name</key>
					<string>keyword.operator.v8.log</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?x)
  \b(
    %
  )\s</string>
					<key>name</key>
					<string>keyword.operator.v8.log</string>
				</dict>
			</array>
		</dict>
		<key>path</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.other.path.v8.log</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(([\w\d\.\-\_]+)?(:)?((([\/|\/\/|\\|\\\\])[\w\d\.\-\_\ ]+)+)(([\w\d\-\_\ ]+)(\.)([a-zA-Z\.]+)))(:)?</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.other.path.v8.log</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(([\w\d\-\_]+)(\.)(js|coffee|ts|ls))(:)</string>
				</dict>
			</array>
		</dict>
		<key>regexp</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.v8.log</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.regexp.v8.log</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(RegExp):\s*(.*?)$</string>
				</dict>
			</array>
		</dict>
		<key>section</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.v8.log</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.other.v8.log</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.v8.log</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(\[)(.*?)(\])</string>
					<key>name</key>
					<string>meta.tag.section.v8.log</string>
				</dict>
			</array>
		</dict>
		<key>support</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?x)
  \b(
    LazyCompile|RegExp|Stub|Function|Builtin|
    StorePolymorphicIC|KeyedStoreIC|
    KeyedStorePolymorphicIC|
    StoreMegamorphic|Eval|Script|Handler
  )\b</string>
					<key>name</key>
					<string>support.class.v8.log</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.log</string>
	<key>uuid</key>
	<string>68d9a4a1-519b-48f0-ab7a-9d78d30c2db5</string>
</dict>
</plist>
